import { motion } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Shield, FileText, Users, Lock, RefreshCw, Truck } from 'lucide-react';

export default function Policies() {
  return (
    <div className="min-h-screen pt-16">
      <div className="container px-4 sm:px-6 lg:px-8 py-24">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h1 className="text-4xl font-bold mb-6">Policies & Terms</h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Our commitment to transparency, privacy, and professional standards
          </p>
        </motion.div>

        <div className="max-w-4xl mx-auto space-y-8">
          {/* Terms & Conditions */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            viewport={{ once: true }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-primary" />
                  Terms & Conditions
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <p className="text-muted-foreground">
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                  </p>

                  <p className="text-muted-foreground">
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://starset-solutions.com/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                  </p>

                  <p className="text-muted-foreground">
                    The Platform is owned by 9481041558 with its registered office at Near Jija Mata School Vidya Nagar, a company incorporated under the Companies Act, 1956 (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Agreement to Terms</h4>
                  <p className="text-muted-foreground">
                    Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">User Obligations</h4>
                  <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                    <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration</li>
                    <li>You shall be responsible for all acts done through the use of your registered account on the Platform</li>
                    <li>You agree to pay us the charges associated with availing the Services</li>
                    <li>You agree not to use the Platform for any purpose that is unlawful, illegal or forbidden by these Terms</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Intellectual Property</h4>
                  <p className="text-muted-foreground">
                    The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Limitation of Liability</h4>
                  <p className="text-muted-foreground">
                    Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Indemnification</h4>
                  <p className="text-muted-foreground">
                    You shall indemnify and hold harmless Platform Owner, its affiliates, group companies and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Governing Law</h4>
                  <p className="text-muted-foreground">
                    These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in India.
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Privacy Policy */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            viewport={{ once: true }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Shield className="h-5 w-5 text-primary" />
                  Privacy Policy
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <h4 className="font-semibold">Introduction</h4>
                  <p className="text-muted-foreground">
                    This Privacy Policy describes how https://starset-solutions.com/ and its affiliates (collectively "9481041558", we, our, us") collect, use, share, protect or otherwise process your information/personal data through our website (hereinafter referred to as Platform). We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Collection</h4>
                  <p className="text-muted-foreground">We collect your personal data when you use our Platform, services or otherwise interact with us during the course of our relationship. Some of the information that we may collect includes but is not limited to:</p>
                  <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                    <li>Personal data/information provided during sign-up/registering such as name, date of birth, address, telephone/mobile number, email ID</li>
                    <li>Any information shared as proof of identity or address</li>
                    <li>Bank account or credit or debit card or other payment instrument information (with your consent)</li>
                    <li>Biometric information such as facial features or physiological information (when opted for certain features)</li>
                    <li>Your behavior, preferences, and other information you choose to provide on our Platform</li>
                    <li>Transaction information on Platform and third-party business partner platforms</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Usage</h4>
                  <p className="text-muted-foreground">We use personal data to:</p>
                  <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                    <li>Provide the services you request</li>
                    <li>Assist sellers and business partners in handling and fulfilling orders</li>
                    <li>Enhance customer experience and resolve disputes</li>
                    <li>Troubleshoot problems and inform you about offers, products, services, and updates</li>
                    <li>Customize your experience and detect/protect against error, fraud and criminal activity</li>
                    <li>Enforce our terms and conditions and conduct marketing research, analysis and surveys</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Sharing</h4>
                  <p className="text-muted-foreground">
                    We may share your personal data internally within our group entities, affiliates, and with third parties such as sellers, business partners, logistics partners, payment processors, and government agencies when required by law or to prevent fraudulent activities.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Security Precautions</h4>
                  <p className="text-muted-foreground">
                    To protect your personal data from unauthorized access or disclosure, loss or misuse we adopt reasonable security practices and procedures. Once your information is in our possession, we adhere to our security guidelines to protect it against unauthorized access and offer the use of a secure server.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Data Deletion and Retention</h4>
                  <p className="text-muted-foreground">
                    You have an option to delete your account by visiting your profile and settings on our Platform. We retain your personal data for a period no longer than required for the purpose for which it was collected or as required under applicable law. We may continue to retain your data in anonymized form for analytical and research purposes.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Your Rights</h4>
                  <p className="text-muted-foreground">
                    You may access, rectify, and update your personal data directly through the functionalities provided on the Platform. You have the option to withdraw your consent by writing to the Grievance Officer.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Consent</h4>
                  <p className="text-muted-foreground">
                    By visiting our Platform or providing your information, you consent to the collection, use, storage, disclosure and processing of your information in accordance with this Privacy Policy. You consent to us contacting you through SMS, instant messaging apps, call and/or e-mail for the purposes specified in this Privacy Policy.
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Refund and Cancellation Policy */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            viewport={{ once: true }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <RefreshCw className="h-5 w-5 text-primary" />
                  Refund and Cancellation Policy
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-muted-foreground">
                  This refund and cancellation policy outlines how you can cancel or seek a refund for a product/service that you have purchased through the Platform.
                </p>

                <div className="space-y-3">
                  <h4 className="font-semibold">Cancellation Policy</h4>
                  <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                    <li>Cancellations will only be considered if the request is made within 5 days of placing the order</li>
                    <li>Cancellation requests may not be entertained if orders have been communicated to sellers/merchants and shipping has been initiated</li>
                    <li>If the product is out for delivery, you may choose to reject the product at the doorstep</li>
                    <li>9481041558 does not accept cancellation requests for perishable items like flowers, eatables, etc.</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Refund Conditions</h4>
                  <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                    <li>Refund/replacement can be made if the user establishes that the quality of the product delivered is not good</li>
                    <li>In case of receipt of damaged or defective items, please report to our customer service team within 5 days</li>
                    <li>If you feel the product received is not as shown on the site or as per your expectations, bring it to our customer service within 5 days</li>
                    <li>For products with manufacturer warranty, please refer issues directly to the manufacturer</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Refund Processing</h4>
                  <p className="text-muted-foreground">
                    In case of any refunds approved by 9481041558, it will take 10 days for the refund to be processed to you.
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Return Policy */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            viewport={{ once: true }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Users className="h-5 w-5 text-primary" />
                  Return Policy
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <h4 className="font-semibold">Return Timeframe</h4>
                  <p className="text-muted-foreground">
                    We offer refund/exchange within first 5 days from the date of your purchase. If 5 days have passed since your purchase, you will not be offered a return, exchange or refund of any kind.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Return Eligibility</h4>
                  <p className="text-muted-foreground">In order to become eligible for a return or an exchange:</p>
                  <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                    <li>The purchased item should be unused and in the same condition as you received it</li>
                    <li>The item must have original packaging</li>
                    <li>If the item was purchased on sale, it may not be eligible for return/exchange</li>
                    <li>Only items found defective or damaged are replaced by us (based on exchange request)</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Return Process</h4>
                  <p className="text-muted-foreground">
                    For accepted return/exchange requests, once your returned product is received and inspected by us, we will send you an email notification. If approved after quality check, your request will be processed in accordance with our policies.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Exempted Categories</h4>
                  <p className="text-muted-foreground">
                    Certain categories of products/items are exempted from returns or refunds. Such categories will be identified to you at the time of purchase.
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Shipping Policy */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            viewport={{ once: true }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Truck className="h-5 w-5 text-primary" />
                  Shipping Policy
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <h4 className="font-semibold">Shipping Methods</h4>
                  <p className="text-muted-foreground">
                    The orders for users are shipped through registered domestic courier companies and/or speed post only.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Delivery Timeline</h4>
                  <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                    <li>Orders are shipped within 15 days from the date of order and/or payment</li>
                    <li>Delivery timeline is subject to courier company/post office norms</li>
                    <li>Platform Owner shall not be liable for any delay in delivery by the courier company/postal authority</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Delivery Address</h4>
                  <p className="text-muted-foreground">
                    Delivery of all orders will be made to the address provided by the buyer at the time of purchase. Delivery of our services will be confirmed on your email ID as specified at the time of registration.
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">Shipping Costs</h4>
                  <p className="text-muted-foreground">
                    If there are any shipping costs levied by the seller or the Platform Owner, the same is not refundable.
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Grievance Officer */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            viewport={{ once: true }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Lock className="h-5 w-5 text-primary" />
                  Grievance Officer
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <h4 className="font-semibold">Contact Information</h4>
                  <div className="bg-muted p-4 rounded-lg">
                    <p className="font-medium">Name of the Office: Starset - Solutions</p>
                    <p className="font-medium">Designation: Founder and CEO</p>
                    <p className="font-medium">Name: Sheshank Sonji</p>
                    <p className="font-medium">Address: Near Jija Mata School Vidya Nagar Bidar</p>
                    <p className="font-medium">Contact: 9481041558</p>
                    <p className="font-medium">Time: Monday - Friday (9:00 - 18:00)</p>
                  </div>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold">How to Contact</h4>
                  <p className="text-muted-foreground">
                    For any grievances, complaints, or concerns regarding our services, privacy policy, or terms of use, please contact our Grievance Officer during the specified business hours. We are committed to addressing your concerns promptly and effectively.
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <Separator className="my-8" />

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7 }}
            viewport={{ once: true }}
            className="text-center text-muted-foreground"
          >
            <p className="mb-2">
              <strong>Last Updated:</strong> December 28, 2024
            </p>
            <p className="mb-2">
              For questions about these policies, please contact us at{' '}
              <a href="mailto:starsetconsulting@gmail.com" className="text-primary hover:underline">
                starsetconsulting@gmail.com
              </a>
            </p>
            <p>
              Or call us at{' '}
              <a href="tel:9481041558" className="text-primary hover:underline">
                9481041558
              </a>
            </p>
          </motion.div>
        </div>
      </div>
    </div>
  );
}